# Generated by Django 5.0.4 on 2024-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='center',
            old_name='websyte',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='center',
            new_name='object',
        ),
    ]
